[project]
name = "wo_wip"
authors = [
    { name = "NestERP / Manifold SA" }
]
description = "Works Order WIP operator screen"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "wo_wip"
