[project]
name = "wo_wip"
authors = [
    { name = "NestERP / Manifold SA", email = "ops@syncflo.co.za" }
]
description = "Works Order WIP operator screen for shop floor"
requires-python = ">=3.10"
readme = "README.md"
license = { file = "license.txt" }
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "wo_wip"


[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
